### ISSUE TITLE
Initializer country code restriction fails

### ISSUE THREAD

**Issue by rosskevin** [code-and-effect/effective_addresses#7]
`config.country_codes = ['US', 'CA']` fails with 

```ruby
ActionView::Template::Error (undefined method `coded' for #<Array:0x007feda5c0a900>):
    12:   = fa.input :address2, :label => 'Address 2'
    13:   = fa.input :city, :placeholder => 'City', :required => required
    14: 
    15:   = fa.input :country_code, :as => :select, :label => 'Country', :prompt => 'Choose country...', :collection => region_options_for_simple_form_select(), :input_html => {'data-effective-address-country' => uuid}, :required => required
    16: 
    17:   - if fa.object.try(:country_code).present?
    18:     = fa.input :state_code, :as => :select, :label => 'Province / State', :prompt => 'Please choose a country first', :collection => region_options_for_simple_form_select(Carmen::Country.coded(fa.object.country_code).subregions), :input_html => {'data-effective-address-state' => uuid}, :required => required
  effective_addresses (1.2.2) app/helpers/effective_addresses_helper.rb:43:in `block in region_options_for_simple_form_select'
  effective_addresses (1.2.2) app/helpers/effective_addresses_helper.rb:42:in `each'
  effective_addresses (1.2.2) app/helpers/effective_addresses_helper.rb:42:in `region_options_for_simple_form_select'
  effective_addresses (1.2.2) app/views/effective/addresses/_address_fields_simple_form.html.haml:15:in `block in ___sers_kross__rvm_gems_ruby_______af_core_gems_effective_addresses_______app_views_effective_addresses__address_fields_simple_form_html_haml___1014979389152356289_70329297902560'
  /Users/kross/.rvm/gems/ruby-2.2.0@came/bundler/gems/haml-7c7c16930b7f/lib/haml/helpers.rb:379:in `call'
```

```ruby
Showing /Users/kross/.rvm/gems/ruby-2.2.0@af_core/gems/effective_addresses-1.2.2/app/views/effective/addresses/_address_fields_simple_form.html.haml where line #15 raised:

undefined method `coded' for #<Array:0x007feda5c0a900>
Extracted source (around line #43):
      EffectiveAddresses.country_codes_priority.reverse.each do |code|
        if (country = countries.coded(code))
          collection.insert(0, [country.name, country.code])
        end
      end
```

The `:all` option works fine.

**Comment by rosskevin** [comment]
Looking at this one now.

**Comment by matt-riemer** [comment]
Great fix, thanks
